export const FETCH_PENDING_IMAGES = "FETCH_PENDING_IMAGES";
export const FETCH_APPROVED_IMAGES = "FETCH_APPROVED_IMAGES";
export const FETCH_REJECTED_IMAGES = "FETCH_REJECTED_IMAGES";
export const APPROVE_IMAGE = "APPROVE_IMAGE";
export const REJECT_IMAGE = "REJECT_IMAGE";
